export const GET_ALL_INGREDIENTS = 'GET_ALL_INGREDIENTS';
export const GET_INGREDIENTS_FOR_CONSTRUCTOR =
  'GET_INGREDIENTS_FOR_CONSTRUCTOR';
export const ADD_INGREDIENT_DETAILS = 'ADD_INGREDIENT_DETAILS';
export const DEL_INGREDIENT_DETAILS = 'DEL_INGREDIENT_DETAILS';
export const GET_ORDER_ID = 'GET_ORDER_ID';
