export const WS_CONNECTION_PRIVATE_START = 'WS_CONNECTION_PRIVATE_START';
export const WS_CONNECTION_PRIVATE_SUCCESS = 'WS_CONNECTION_PRIVATE_SUCCESS';
export const WS_CONNECTION_PRIVATE_ERROR = 'WS_CONNECTION_PRIVATE_ERROR';
export const WS_CONNECTION_PRIVATE_CLOSED = 'WS_CONNECTION_PRIVATE_CLOSED';
export const WS_GET_MESSAGE_PRIVATE = 'WS_GET_MESSAGE_PRIVATE';
export const WS_SEND_MESSAGE_PRIVATE = 'WS_SEND_MESSAGE_PRIVATE';
